# Dockerfile for building image that contains software stack provisioned by Ansible.
#
# Version  1.0
#


# pull base image
FROM williamyeh/ansible:master-centos6-onbuild

MAINTAINER William Yeh <william.pjyeh@gmail.com>


#
# build phase
#

RUN echo "===> Installing the missing "tar" utility for Docker image..."  && \
    yum -y install tar

RUN echo "===> Patching test.yml playbook to exclude roles that are unused in Docker version..."  && \
    sed -i -e 's/\(\- williamyeh\)/#\1/g' test.yml

ENV PLAYBOOK test.yml
RUN ansible-playbook-wrapper -vvv



#
# test phase
#

RUN echo "==> Removing PID files..."  && \
    rm -f /var/run/prometheus/*

RUN echo "===> Installing curl for testing purpose..."  && \
    yum -y install curl initscripts


VOLUME ["/data"]
ENV    RESULT     /data/result-centos6

CMD  \
     sed -i -e 's/localhost/mongo/' /etc/init.d/mongodb_exporter  && \
     service mongodb_exporter start  &&  sleep 30  && \
     curl http://localhost:9001/metrics  > $RESULT
