sudo: true
services:
    - docker

before_install:
    - docker info
    - docker version

    - docker build  -f test/Dockerfile-ubuntu14.04  -t mongodb_exporter_trusty   .
    - docker build  -f test/Dockerfile-ubuntu12.04  -t mongodb_exporter_precise  .
    - docker build  -f test/Dockerfile-debian8      -t mongodb_exporter_jessie   .
    - docker build  -f test/Dockerfile-debian7      -t mongodb_exporter_wheezy   .
    - docker build  -f test/Dockerfile-centos7      -t mongodb_exporter_centos7  .
    ###- docker build  -f test/Dockerfile-centos6      -t mongodb_exporter_centos6  .

script:
    - docker run --name mongo -d mongo

    - docker run -v $(pwd):/data --link mongo:mongo mongodb_exporter_trusty
    - docker run -v $(pwd):/data --link mongo:mongo mongodb_exporter_precise
    - docker run -v $(pwd):/data --link mongo:mongo mongodb_exporter_jessie
    - docker run -v $(pwd):/data --link mongo:mongo mongodb_exporter_wheezy
    - docker run -v $(pwd):/data --link mongo:mongo mongodb_exporter_centos7
    ###- docker run -v $(pwd):/data --link mongo:mongo mongodb_exporter_centos6

    - echo "==> Validating the test results..."
    - grep '^mongodb_connections' result-ubuntu14.04
    - grep '^mongodb_connections' result-ubuntu12.04
    - grep '^mongodb_connections' result-debian8
    - grep '^mongodb_connections' result-debian7
    - grep '^mongodb_connections' result-centos7
    ###- grep '^mongodb_connections' result-centos6

notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/
