---
# file: handlers/main.yml
#

- name: restart mongodb_exporter
  service: name=mongodb_exporter state=restarted

- name: reload mongodb_exporter
  service: name=mongodb_exporter state=reloaded

- name: stop mongodb_exporter
  service: name=mongodb_exporter state=stopped
